version: "3.5"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "itsonlylocal"
    volumes:
      - ./mysql_data:/var/lib/mysql
