version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306" # should be deleted in production
    environment:
      MYSQL_ROOT_PASSWORD: "itsonlylocal"
    volumes:
      - ./mysql_data:/var/lib/mysql

  python:
    image: mcr.microsoft.com/playwright/python:v1.27.0-focal
    container_name: python
    working_dir: /usr/app
    ports:
      - "8888:8888" # for jupyter notebook
    volumes:
      - ../app:/usr/app
    tty: true
    command:
      - /bin/bash
    links:
      - mariadb

